<a href="https://colab.research.google.com/github/kolhehemant/python100days/blob/master/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
%matplotlib notebook
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [12]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [15]:
arr = np.array([1,2,3])
arr
type(arr)

numpy.ndarray

In [16]:
arr += 2
arr

array([3, 4, 5])

In [21]:
arr = np.random.random((4,3) )
arr
arr.reshape(6,2)

array([[0.68064671, 0.84126289],
       [0.45962806, 0.12136397],
       [0.63371737, 0.82587323],
       [0.52255879, 0.60905803],
       [0.06171293, 0.58424595],
       [0.55342109, 0.51302234]])

In [26]:
arr = np.arange(1,10,3)
arr

array([1, 4, 7])

In [38]:
arr = np.linspace(1,20,4)
arr

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [53]:
arr1 = [[1,2,3] , [4,5,6] , [7,8,9]]
arr2 = [[10,11,12] , [14,15,16] , [17,18,19]]
arr3 = np.array(arr1) + np.array(arr2)
print(arr3)
arr3_flatten = arr3.flatten()
arr3_flatten



[[11 13 15]
 [18 20 22]
 [24 26 28]]


array([11, 13, 15, 18, 20, 22, 24, 26, 28])

In [58]:
arr3[1:2,1:2]

array([[20]])

In [79]:
arr1 = [ [1,2,3] ,
         [4,5,6] ,
         [7,8,9] ]

arr2 = [ [10,11,12] ,
         [14,15,16] ,
         [17,18,19]]

arr3 = np.hstack((arr2,arr1))
print(arr3)
print("======")
arr5 = np.hsplit(arr3,3)
print(arr5)
print("======")
arr4 = np.vstack((arr2,arr1))
print(arr4)
print("======")
arr6 = np.hsplit(arr4,3)
print(arr6)
print("======")


[[10 11 12  1  2  3]
 [14 15 16  4  5  6]
 [17 18 19  7  8  9]]
[array([[10, 11],
       [14, 15],
       [17, 18]]), array([[12,  1],
       [16,  4],
       [19,  7]]), array([[2, 3],
       [5, 6],
       [8, 9]])]
[[10 11 12]
 [14 15 16]
 [17 18 19]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[array([[10],
       [14],
       [17],
       [ 1],
       [ 4],
       [ 7]]), array([[11],
       [15],
       [18],
       [ 2],
       [ 5],
       [ 8]]), array([[12],
       [16],
       [19],
       [ 3],
       [ 6],
       [ 9]])]


In [75]:
arr1 = [[1,2,3] , [4,5,6] , [7,8,9]]
arr2 = [[10,11,12] , [14,15,16] , [17,18,19]]
aar3 = np.concatenate((arr1,arr2),axis=1)
print(arr3)
arr4 = np.concatenate((arr1,arr2),axis=0)
print(arr4)

[[10 11 12  1  2  3]
 [14 15 16  4  5  6]
 [17 18 19  7  8  9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [14 15 16]
 [17 18 19]]


In [14]:
import numpy as np
str_arr = np.array(['a','b','c','d'])
str_arr[2] == 'c'

True

In [12]:
print(str_arr[str_arr == 'c'])

['c']


In [18]:
lst = [4,8,12,16,20]
print(np.array(lst) + 2)

[ 6 10 14 18 22]


In [29]:
import numpy as np
np.linspace((1,2,3),(10,20,30),4 , dtype = np.int8)


array([[ 1,  2,  3],
       [ 4,  8, 12],
       [ 7, 14, 21],
       [10, 20, 30]], dtype=int8)

In [42]:
np.arange(3*4*5).reshape(3,4,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [63]:
firts_arr = np.arange(1,11)
second_arr = np.arange(11,21)
print("first arr is , " , firts_arr)
print("second arr is , " , second_arr)

first arr is ,  [ 1  2  3  4  5  6  7  8  9 10]
second arr is ,  [11 12 13 14 15 16 17 18 19 20]


In [74]:
con_arr = np.concatenate((firts_arr,second_arr),axis=0)
print(con_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [62]:
np.concatenate((firts_arr,second_arr) , axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
third_arr = np.array( [ [1,2,3,4] , [5,6,7,8] ])
fourth_arr = np.array( [ [11,12,13,14] , [15,16,17,18] ])
print("third_arr is , " , third_arr)
print("fourth_arr is , " , fourth_arr)

fifth_con_arr = np.concatenate((third_arr,fourth_arr),axis=1)
print("fifth_con_arr is , " , fifth_con_arr)

print("dim fifth_con_arr is , " , fifth_con_arr.shape)

sixth_con_arr = np.concatenate((third_arr,fourth_arr),axis=0)
print("sixth_con_arr is , " , sixth_con_arr)
print("dim sixth_con_arr is , " , sixth_con_arr.shape)


third_arr is ,  [[1 2 3 4]
 [5 6 7 8]]
fourth_arr is ,  [[11 12 13 14]
 [15 16 17 18]]
fifth_con_arr is ,  [[ 1  2  3  4 11 12 13 14]
 [ 5  6  7  8 15 16 17 18]]
dim fifth_con_arr is ,  (2, 8)
sixth_con_arr is ,  [[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]
 [15 16 17 18]]
dim sixth_con_arr is ,  (4, 4)


In [80]:
firts_arr = np.arange(1,11)
print(firts_arr)
firts_arr[2::3]
print(firts_arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
10
[ 1  2  3  4  5  6  7  8  9 10]


In [88]:
firts_arr = np.arange(6).reshape(2,3)
print(firts_arr)
print(np.transpose(firts_arr) )
print(np.transpose(firts_arr) , (1,0))


[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]] (1, 0)


In [79]:
third_arr = np.array( [ [1,2,3,4] , [4,5,3,1] ])
fourth_arr = np.array( [ [11,12,13,14] , [12,13,11,18] ])
print(third_arr)

[[1 2 3 4]
 [4 5 3 1]]


In [91]:
arr1 = np.array([2,4,6,8,10])
arr1.prod()


3840